### ISSUE TITLE
Build table group component

### ISSUE THREAD

**Issue by sjmog** [makersacademy/style_guide#87]
We need tables, bro! First up, a group to drop into templates. Then, a one-up-table template that just wraps around a table :).

Wireframe tbc.

**Comment by sjmog** [comment]
Wireframe: https://makersacademy.mybalsamiq.com/projects/newsitewireframes/one-up-table

**Comment by sjmog** [comment]
![](https://makersacademy.mybalsamiq.com/mockups/3184259.png?key=4170896665ca7444d80f24009d93fc25e1ce8ea2)

**Comment by sjmog** [comment]
Notes:

1) Component is 100% width up to 1024px, max-width 960px, then min-width 960px and 61.8% full screen width on larger
2) Component height is flexible and expands as needed.
3) Acceptable modifiers: --striped
4) Acceptable locals: modifiers, parent, columns
5) Table then becomes responsive for mobile, using top example here https://css-tricks.com/responsive-data-table-roundup/

**Comment by sjmog** [comment]
Suggested YAML:

```yaml
columns:
  - header: "variable"
    - row: "modifiers"
    - row: "parent"
    - row: "titles"
  - header: "description"
    - row: "Any modifiers (see modifiers)"
    - row: "The element's parent"
    - row: "Any titles to be rendered, as: { modifiers: [], text: String } (see title)"
```

**Comment by sjmog** [comment]
YAML translated to Ruby `locals`:

```ruby
modifiers: "striped",
parent: nil,
columns: [
  {
    header: "variable",
    rows: [
      "modifiers",
      "parent",
      "titles"
    ]
  },
  {
    header: "description",
    rows: [
      "Any modifiers (see modifiers)",
      "The element's parent",
      "Any titles to be rendered"
    ]
  }
]
```

**Comment by pitchinvasion** [comment]
I think I'd find the yaml pretty confusing, you normally add data grouped per row rather than column, could we not do

```yaml
headers:
  - first
  - second
  - last
rows:
  - row:
    - "hello"
    - "there"
    - "another"
  - row:
    - "hello"
    - "there"
    - "another"
```

**Comment by sjmog** [comment]
I hear you, but the way we have it we can group common data together, which I think is more useful when copy-pasting data from elsewhere.

I.e. see the YAML I did above. Can we try with this, and if there are issues, refactor it later? I want to get the table in the glossary up.

**Comment by sjmog** [comment]
Roi suggests doing it by columns is easier to keep on top of the data relations - say you had these two alternatives:

```yaml
columns:
  - header: "Quarter"
    - row: "Q1"
    - row: "Q2"
    - row: "Q3"
  - header: "Results"
    - row: 25400
    - row: 28900
    - row: 31600
```

I think that is easier to understand when inputting (and harder to fuck up) than:

```yaml
headers:
  - "Quarter"
  - "Results"
rows:
  - row:
    - "Q1"
    - 25400
  - row:
    - "Q2"
    - 28900
  - row:
    - "Q3"
    - 31600
```
